---
source: crates/ruff_linter/src/rules/flake8_trio/mod.rs
---
TRIO100.py:5:5: TRIO100 A `with trio.fail_after(...):` context does not contain any `await` statements. This makes it pointless, as the timeout can only be triggered by a checkpoint.
  |
4 |   async def func():
5 |       with trio.fail_after():
  |  _____^
6 | |         ...
  | |___________^ TRIO100
  |

TRIO100.py:15:5: TRIO100 A `with trio.move_on_after(...):` context does not contain any `await` statements. This makes it pointless, as the timeout can only be triggered by a checkpoint.
   |
14 |   async def func():
15 |       with trio.move_on_after():
   |  _____^
16 | |         ...
   | |___________^ TRIO100
   |


