---
source: crates/ruff_linter/src/rules/flake8_trio/mod.rs
---
TRIO100.py:5:5: TRIO100 A `with trio.fail_after(...):` context does not contain any `await` statements. This makes it pointless, as the timeout can only be triggered by a checkpoint.
  |
4 |   async def foo():
5 |       with trio.fail_after():
  |  _____^
6 | |         ...
  | |___________^ TRIO100
7 |   
8 |   async def foo():
  |

TRIO100.py:13:5: TRIO100 A `with trio.move_on_after(...):` context does not contain any `await` statements. This makes it pointless, as the timeout can only be triggered by a checkpoint.
   |
12 |   async def foo():
13 |       with trio.move_on_after():
   |  _____^
14 | |         ...
   | |___________^ TRIO100
15 |   
16 |   async def foo():
   |


